### ISSUE TITLE
IOException: SIGPIPE, RtcAsyncContext.writeEvent(RtcAsyncContext.java:97)

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1124]
I use apache-tomcat-8.5.5 and project created from cms-app-archetype:

> 		<cms.version>3.2.6800-ed293d</cms.version>
>		<dari.version>3.2.2348-dcc2b2</dari.version>

Sometime I got this error message in Tomcat logs. Whats wrong? It looks that client close SSE stream or something similar. Should I worry about it? 

> 13-Dec-2016 15:07:05.520 INFO [pool-1-thread-1] org.apache.coyote.AbstractProcessor.setErrorState An error occurred in processing while on a non-container thread. The connection will be closed immediately
 java.io.IOException: Roura přerušena (SIGPIPE)
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441)
	at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:514)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:243)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1494)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:284)
	at org.apache.coyote.Response.action(Response.java:167)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:336)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:303)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:541)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
	at com.psddev.cms.rtc.RtcAsyncContext.writeEvent(RtcAsyncContext.java:97)
	at com.psddev.cms.rtc.RtcAsyncContextPingRunnable.run(RtcAsyncContextPingRunnable.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Many thanks for reply.
O.

**Comment by rhino88** [comment]
Hi Typografikon,

The error can be safely ignored. This may happen in scenarios where Tomcat is trying to write to the browser, but the browser has already disconnected and Tomcat has not detected the disconnect.

We will open a ticket to suppress the error in the logs.

Thanks for the feedback!

**Comment by Typografikon** [comment]
Thanks for quick response. It will be nice to suppress these error in logs because currently it looks like software is broken.

I submit one more issue about annoying exceptions, now it is about build process - see #1125
