### ISSUE TITLE
Data is missing with @Embedded

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#1141]
Hi,

I am getting below error and data i added is missing (Restored Work In Progress from Dec 19, 2016 10:44:06 PM Clear changes).  This issue is happening when i am applying @Embedded on List<EntityAB>.

java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:216)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:120)
	at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:800)
	at org.apache.coyote.Response.action(Response.java:172)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:366)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:334)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:594)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:306)
	at com.psddev.cms.rtc.RtcAsyncContext.writeEvent(RtcAsyncContext.java:97)
	at com.psddev.cms.rtc.RtcAsyncContextPingRunnable.run(RtcAsyncContextPingRunnable.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Dec 19, 2016 9:33:56 PM org.apache.catalina.connector.CoyoteAdapter asyncDispatch
SEVERE: An exception or error occurred in the container during the request processing
java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [COMPLETING]
	at org.apache.coyote.AsyncStateMachine.asyncError(AsyncStateMachine.java:367)
	at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:860)
	at org.apache.coyote.Request.action(Request.java:345)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:438)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:305)
	at org.apache.coyote.http11.AbstractHttp11Processor.asyncDispatch(AbstractHttp11Processor.java:1681)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:616)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Please suggest.

**Comment by rhino88** [comment]
This error indicates that Solr is not configured correctly. Double check that your Solr is configured as explained in the [Advanced Installation](http://docs.brightspot.com/cms/developers-guide/installation/advanced.html) guide.  Alternatively you can use our [Quick Installation](http://docs.brightspot.com/cms/developers-guide/installation/quick.html) to get up and running without any configuration.
