### ISSUE TITLE
Locked threads preventing Tomcat starting

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/brightspot-cms#1337]
We have a Brightspot 2.4 site that has beeb running fine for 3–4 years. However the application now no longer starts, with locked threads.

```"http-apr-8080-exec-1@5604" daemon prio=5 tid=0x17 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks Thread #3@5601
	 blocks Thread #2@5602
	 blocks http-apr-8080-exec-6@5639
	 blocks http-apr-8080-exec-5@5638
	 blocks http-apr-8080-exec-4@5635
	 blocks http-apr-8080-exec-3@5594
	 blocks http-apr-8080-exec-2@5595
	 waiting for Thread #2@5602 to release lock on <0x15f5> (a java.util.logging.ConsoleHandler)
	  at java.util.logging.StreamHandler.publish(StreamHandler.java:191)
	  at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:105)
	  at java.util.logging.Logger.log(Logger.java:616)
	  at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:588)
	  at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:305)
	  at com.psddev.dari.db.DatabaseEnvironment.refreshGlobals(DatabaseEnvironment.java:205)
	  - locked <0x15f6> (a com.psddev.dari.db.DatabaseEnvironment)
	  at com.psddev.dari.db.DatabaseEnvironment$2.run(DatabaseEnvironment.java:140)
	  at com.psddev.dari.util.Once.ensure(Once.java:63)
	  - locked <0x15f2> (a com.psddev.dari.db.DatabaseEnvironment$2)
	  at com.psddev.dari.db.DatabaseEnvironment.getTypesByGroup(DatabaseEnvironment.java:732)
	  at com.psddev.dari.db.Query.getDatabase(Query.java:282)
	  at com.psddev.dari.db.Query.first(Query.java:1477)
	  at com.psddev.dari.db.UpdateTrackable$Static.isUpdated(UpdateTrackable.java:45)
	  at com.psddev.dari.db.WebResourceOverrideFilter$2$1.update(WebResourceOverrideFilter.java:57)
	  at com.psddev.dari.util.PeriodicCache.refresh(PeriodicCache.java:84)
	  - locked <0x15f7> (a com.psddev.dari.db.WebResourceOverrideFilter$2$1)
	  at com.psddev.dari.util.PeriodicCache.<init>(PeriodicCache.java:33)
	  at com.psddev.dari.util.PeriodicCache.<init>(PeriodicCache.java:60)
	  at com.psddev.dari.db.WebResourceOverrideFilter$2$1.<init>(WebResourceOverrideFilter.java:48)
	  at com.psddev.dari.db.WebResourceOverrideFilter$2.create(WebResourceOverrideFilter.java:48)
	  at com.psddev.dari.db.WebResourceOverrideFilter$2.create(WebResourceOverrideFilter.java:44)
	  at com.psddev.dari.util.Lazy$1.run(Lazy.java:32)
	  at com.psddev.dari.util.Once.ensure(Once.java:63)
	  - locked <0x15f0> (a com.psddev.dari.util.Lazy$1)
	  at com.psddev.dari.util.Lazy.get(Lazy.java:50)
	  at com.psddev.dari.db.WebResourceOverrideFilter.doDispatch(WebResourceOverrideFilter.java:93)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.ResourceFilter.doRequest(ResourceFilter.java:64)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.PingFilter.doRequest(PingFilter.java:38)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.LocalStorageFilter.doRequest(LocalStorageFilter.java:71)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.HtmlApiFilter.doRequest(HtmlApiFilter.java:42)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.SessionIdFilter.doRequest(SessionIdFilter.java:35)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.PageContextFilter.doRequest(PageContextFilter.java:60)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.MultipartRequestFilter.doRequest(MultipartRequestFilter.java:35)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.StatsFilter.doRequest(StatsFilter.java:50)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.ProfilerFilter.doDispatch(ProfilerFilter.java:34)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.DebugFilter.doRequest(DebugFilter.java:237)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.DebugFilter.doDispatch(DebugFilter.java:158)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.ResourceFilter.doRequest(ResourceFilter.java:64)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:200)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.DebugFilter$SettingsOverrideFilter.doRequest(DebugFilter.java:737)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.LogCaptureFilter.doRequest(LogCaptureFilter.java:43)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.HeaderResponseFilter.doRequest(HeaderResponseFilter.java:34)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:200)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.Utf8Filter.doRequest(Utf8Filter.java:93)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	  at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	  at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	  at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2391)
	  - locked <0x15f8> (a org.apache.tomcat.util.net.AprEndpoint$AprSocketWrapper)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	  at java.lang.Thread.run(Thread.java:748)
```

```"http-apr-8080-exec-6@5639" daemon prio=5 tid=0x29 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for http-apr-8080-exec-1@5604 to release lock on <merged>(a com.psddev.dari.util.Lazy$1)
	  at com.psddev.dari.util.Once.ensure(Once.java:60)
	  at com.psddev.dari.util.Lazy.get(Lazy.java:50)
	  at com.psddev.dari.db.WebResourceOverrideFilter.doDispatch(WebResourceOverrideFilter.java:93)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.ResourceFilter.doRequest(ResourceFilter.java:64)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.PingFilter.doRequest(PingFilter.java:38)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.LocalStorageFilter.doRequest(LocalStorageFilter.java:71)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.HtmlApiFilter.doRequest(HtmlApiFilter.java:42)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:407)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.SessionIdFilter.doRequest(SessionIdFilter.java:35)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.PageContextFilter.doRequest(PageContextFilter.java:60)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.MultipartRequestFilter.doRequest(MultipartRequestFilter.java:35)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.StatsFilter.doRequest(StatsFilter.java:50)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.ProfilerFilter.doDispatch(ProfilerFilter.java:34)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.DebugFilter.doRequest(DebugFilter.java:237)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.DebugFilter.doDispatch(DebugFilter.java:158)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.ResourceFilter.doRequest(ResourceFilter.java:64)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:200)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.DebugFilter$SettingsOverrideFilter.doRequest(DebugFilter.java:737)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.LogCaptureFilter.doRequest(LogCaptureFilter.java:43)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.HeaderResponseFilter.doRequest(HeaderResponseFilter.java:34)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:200)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.Utf8Filter.doRequest(Utf8Filter.java:93)
	  at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:403)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:565)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:558)
	  at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:274)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	  at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	  at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	  at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2391)
	  - locked <merged>(a org.apache.tomcat.util.net.AprEndpoint$AprSocketWrapper)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	  at java.lang.Thread.run(Thread.java:748)```

We've isolated this to data in the database (postgres) as we can recreate this issue when copying the production database back to local machines.

Any ideas what this could be?

**Comment by nickdunn** [comment]
Are there caches that can be cleared?

**Comment by nickdunn** [comment]
We've narrowed this down to Dari throwing a validation exception from https://github.com/perfectsense/dari/blob/9f28f38ab157020bc487006fa95d727ae11384c1/db/src/main/java/com/psddev/dari/db/AbstractDatabase.java#L1106

    ```#0000016c-9f5c-dcc6-ad7c-dfdf0e9c0000: [Internal Name] [Must be unique but duplicate at 0000015a-d1b2-da9e-a17a-fbf6c53e0000!], [Java Object Class] [Must be unique but duplicate at 0000015a-d1b2-da9e-a17a-fbf6c53e0000!],```

We have ~1,500 content items of type `0000015a-d1b2-da9e-a17a-fbf6c53e0000` already so it's unclear how there might be a duplicate Object Type.

When I use the Dari `query` page by ID `0000015a-d1b2-da9e-a17a-fbf6c53e0000` I get the Object Type returned. However when I query all Object Type without the ID it returns all of them _except_ this one.

Any ideas?

**Comment by nickdunn** [comment]
This is the last SQL query that runs before the lock:

`2019-08-17 22:52:54 UTC LOG:  execute <unnamed>: SELECT DISTINCT r.id, r.typeid
        FROM record r /*! IGNORE INDEX (PRIMARY) */
        INNER JOIN recordstring4 i1 ON i1.id = r.id AND i1.typeid = r.typeid AND i1.symbolid IN (2)
        WHERE 1 = 1
        AND (((r.id IS NULL OR r.id != '0000016c-a1c8-d83e-a77d-a9cb93c80000'))
        AND (i1.symbolid = 2 AND i1.value IS NOT NULL AND i1.value = 'com.xxx.yyy.staff')) LIMIT 1 OFFSET 0`

Running this query returns the _good_ `staff` content type (ID `0000015a-d1b2-da9e-a17a-fbf6c53e0000`) to which all of our existing content sits under.

So the question is, where did `0000016c-a1c8-d83e-a77d-a9cb93c80000` come from, how did a duplicate get into the database, and is it safe to delete?

**Comment by nickdunn** [comment]
We triaged this back to one of content types ("Staff") having been "trashed". It was appearing in the trash archive in Brightspot. However it didn't have a restore button next to it, so it obviously wasn't archived in the usual way like a content record.

Is anyone aware of how an ObjectType can be trashed in the CMS? As far as I know there's definitely no way in the GUI of doing this!

To fix, we had to find the SQL queries that were made that trashed it in the first place, and reverse them.

**Comment by Firefishy** [comment]
@nickdunn Likely best to close this issue now that we fixed it.

Others: The solution was we found is that an `refreshGlobals()` loads the Global objects on start-up, if it cannot find an object it will attempt to create the object in the database. If there is an existing object that has been deleted from in the CMS (dari record JSON: `cms.content.trashed=true`), the creation fails with an error like `#0000016c-9f5c-dcc6-ad7c-dfdf0e9c0000: [Internal Name] [Must be unique but duplicate at 0000015a-d1b2-da9e-a17a-fbf6c53e0000!], [Java Object Class] [Must be unique but duplicate at 0000015a-d1b2-da9e-a17a-fbf6c53e0000!]`, the app then deadlocks. The solution is to undelete the `0000015a-d1b2-da9e-a17a-fbf6c53e0000` object by amending the database. (or if losing the data of that object type isn't an issue, SQL delete the old entry from `records`)

Manually undeleting record is something like SQL:
```
DELETE from recordstring4 WHERE id = '0000015a-d1b2-da9e-a17a-fbf6c53e0000' and typeid='a1c44719-f1bb-b2af-9c5a-6297287f1822' and symbolid=138 and value='true'`
UPDATE record SET typeid='0000014d-dce9-dbd3-a77d-fcff3b140000', data='\xBYTEA-ENCODED-JSON-OBJECT-WITH cms.content.trashed BITS REMOVED' WHERE id='0000015a-d1b2-da9e-a17a-fbf6c53e0000'
```
