### ISSUE TITLE
QUESTION: What is the max limit for storing a property in a Content object?

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/brightspot-cms#353]
I have a Content object `Offer` & I need to store `codes` in it. 

Currently `codes` is a `Set<String>`

Now I tried to store 10,000 9-character codes in it & I got a MySQL exception,

```
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'offer_codes' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4224)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246)
	at com.snagfilms.util.ImportUsersToRDS.insertOrUpdateSubOffer(ImportUsersToRDS.java:2002)
	at com.snagfilms.social.UpdateRDSData.run(UpdateRDSData.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

How to go about this?

I potentially need to be able to store 100,000 codes in an offer. It even failed for 5,000 codes.

**Comment by tankchintan** [comment]
Never mind, looks like this error is unrelated to CMS
