### ISSUE TITLE
The build doesn't work if 'archetypeArtifactId=cms-content-common-archetype'

### ISSUE THREAD

**Issue by gestern** [perfectsense/brightspot-cms#49]
When I tried to generate and install the portal in OS X Yosemite here is appeared:

# STR:
## 1. mvn archetype:generate
```shell
mvn archetype:generate -B \
    -DarchetypeRepository=http://public.psddev.com/maven \
    -DarchetypeGroupId=com.psddev \
    -DarchetypeArtifactId=cms-content-common-archetype \
    -DarchetypeVersion=2.4-SNAPSHOT \
    -DgroupId=com.example \
    -DartifactId=MyArtifactId \
    -DclassPrefix=ClassPrefix \
    -DnamespaceUri=example.com
```
## 2. mvn install

```shell
mvn clean install
```

## The output with error:

```shell
[INFO] Running "bower-install-simple" task
[INFO] Install Bower Dependencies
[INFO] bower                            error Arguments to path.join must be strings
[INFO] 
[INFO] Stack trace:
[INFO] TypeError: Arguments to path.join must be strings
[INFO]     at path.js:360:15
[INFO]     at Array.filter (native)
[INFO]     at Object.exports.join (path.js:358:36)
[INFO]     at Project._readInstalled (..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/core/Project.js:589:26)
[INFO]     at Project._analyse (..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/core/Project.js:461:14)
[INFO]     at Project.install (..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/core/Project.js:48:17)
[INFO]     at install (..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/commands/install.js:27:20)
[INFO]     at ..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/commands/index.js:21:32
[INFO]     at Promise.apply (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:1078:26)
[INFO]     at Promise.promise.promiseDispatch (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:741:41)
[INFO] 
[INFO] Console trace:
[INFO] Trace
[INFO]     at StandardRenderer.error (..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
[INFO]     at Logger.<anonymous> (..../node_modules/grunt-bower-install-simple/tasks/grunt-bower-install-simple.js:81:22)
[INFO]     at Logger.EventEmitter.emit (events.js:95:17)
[INFO]     at Logger.emit (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
[INFO]     at ..../node_modules/grunt-bower-install-simple/node_modules/bower/lib/commands/index.js:40:20
[INFO]     at _rejected (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:797:24)
[INFO]     at ..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:823:30
[INFO]     at Promise.when (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:1035:31)
[INFO]     at Promise.promise.promiseDispatch (..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:741:41)
[INFO]     at ..../node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/q/q.js:509:49
[INFO] 
[INFO] System info:
[INFO] Bower version: 1.3.12
[INFO] Node version: 0.10.26
[INFO] OS: Darwin 14.0.0 x64
[INFO] Warning: Task "bower-install-simple" failed. Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Any ideas?

**Comment by hyoolim** [comment]
You can fix this manually by changing the version number of `bsp-grunt` module in `package.json` file to `~1.1.1`.

Note that this archetype is still in beta and is meant to be run after the main app archetype referenced in http://www.brightspot.com/docs/2.4/get-started/installation so it doesn't work by itself.
