### ISSUE TITLE
Utility to import data into Dari from a CSV file

### ISSUE THREAD

**Issue by kphenix** [perfectsense/brightspot-cms#68]
I am trying to build a simple command line utility where eventually we can pass a CSV and create from it CMS objects.

In the first instance all I am trying to do is create a CMS object of class Condition and persist it. No main method parameters, no CSV. Just get the plumbings right.
```
    public static void main(String[] args) {
    logger.info("Creating a new Condition CMS item");
    
    Condition condition = new Condition();
    condition.setTitle("foo bar");
    condition.save();
    }
```
When I execute this class I get a stack trace with a familiar No default database!
```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.psddev.dari.util.SettingsException: No default database! (check [dari/defaultDatabase] setting)
    at com.psddev.dari.util.Settings.checkValue(Settings.java:303)
    at com.psddev.dari.util.Settings.getOrError(Settings.java:351)
    at com.psddev.dari.db.Database$Static.getDefaultOriginal(Database.java:218)
    at com.psddev.dari.db.Database$Static.getDefault(Database.java:207)
    at com.psddev.dari.db.State.getDatabase(State.java:147)
    at com.psddev.dari.db.State.save(State.java:2078)
    at com.psddev.dari.db.Record.save(Record.java:358)
    at com.wearefriday.utilities.ImportConditionUtility.main(ImportConditionUtility.java:16)
    ... 6 more
```
I need to be able to run this class with some configuration settings that point to the application database.

I am currently executing this class using the maven exec plugin
`mvn exec:java -Dexec.mainClass="com.wearefriday.utilities.ImportConditionUtility"`

Maybe there is a way to do this in the pom?

Many thanks,
Ioannis

**Comment by hyoolim** [comment]
You can set any configuration settings typically found in `context.xml` in `settings.properties` as long as we can find that file in the Java class path. If you're using Maven, that means you can put it in `src/main/resources` directory. For example, if the entry in `context.xml` looks like:

    <Environment name="dari/defaultDatabase" type="java.lang.String" value="psd" override="false" />

You can set it via `settings.properties` like so:

    dari/defaultDatabase: psd
